export const HOT_MOTIF_ANCHORS = {
  billionaire_rich_poor_romance: [
    "Poor Girl Falls For The Heir Next Door",
    "Billionaire Falls For The Homeless Girl He Saved",
    "Rich Boy Pretends To Be Poor To Find Real Love",
    "The Maid And The Young Master",
    "Scholarship Girl Loved By The Heir Of The Foundation",
    "Tutor Falls For The Rich Family's Lonely Son",
    "Delivery Girl Caught The Billionaire's Heart",
    "Caregiver Loved By The Tycoon She Looked After",
    "Cinderella Of The Charity Gala",
    "Poor Baker Wins The Lonely Heir's Heart",
    "Florist Falls For The Groom Who Owns The City",
    "Mechanic Girl Saved His Midnight Crisis And His Heart",
    "Village Girl Loved By The Heir Hiding In Her Town",
    "Poor Designer Loved By The Billionaire Groom",
    "Rich Heiress Falls For The Boy Who Did Not Know Her Name",
    "Billionaire Hides His Wealth To See Who She Really Loves",
    "Rich Boy Tests His Family By Bringing Home A Poor Girl",
    "He Chose The Poor Bride In Front Of His Family",
    "Poor Bride Rejected By The Old Money Mother",
    "Rich Boy Chooses A Poor Girl At The Charity Gala",
    "Billionaire Mother Blocks A Working Class Bride",
    "Old Money Father Offers Money To Make Her Disappear",
    "Family Replaces The Poor Bride With A Socialite",
    "Rich Mother Asks The Poor Lover To Use The Service Door",
    "Billionaire's Family Tests The Poor Lover With Public Insults",
    "Poor Boy Loved By The Lonely Rich Girl",
    "Poor Boy Falls For The Rich Girl Who Saw Him First",
    "Rich Girl Hides Her Wealth Until The Poor Boy Confesses",
    "Donor's Daughter Loves The Scholarship Boy Her Family Hates",
    "Poor Boy Stands In The Rain Outside Her Mansion",
    "Hidden Heir Loved A Girl Who Only Knew His Other Name",
    "Billionaire Mistakes His Benefactor For A Maid Then Falls For Her",
    "Cinderella Lost Her Shoe At The Charity Gala",
    "Mistaken Identity At The Brand Launch Sparked A Romance",
    "Mistaken Gigolo Was The Heir Who Loved Her First",
    "She Walked Away To Protect Him From His Mother",
    "Poor Lover Returns The Family Ring At The Door",
    "Slow-Burn Confession Under The Old Money Chandelier",
    "Forbidden Romance Between The Heir And His Family's Maid",
    "Rich Man Falls For The Caregiver He Underpaid",
    "Poor Tutor Wins The Billionaire Family's Trust",
    "Heir Brings The Poor Girl Home For Lunar New Year",
    "Public Confession At The Family Gala",
    "Rich Heir Resigns From The Family To Marry Her",
    "Poor Bride Defended By Him Before The Old Money Aunts",
    "Billionaire CEO Falls For The Intern He Almost Fired",
    "Hospital Janitor Saved The Tycoon's Sister At Midnight",
    "Coffee Shop Barista Loved By The VC Who Funded The Cafe Next Door",
    "Hotel Front Desk Girl Wins The Heart Of A Visiting Heir",
    "Single Mother Florist Loved By The Hotel Heir Who Walks His Dog Past Her Shop",
    "Tech Founder Falls For The Cleaning Crew Lead Who Knows His Office Better Than He Does",
    "Pharmacist Loved By The Pharmaceutical Heir Disguised As A New Hire",
    "Music Teacher Loved By The Producer Who Inherited The Studio",
    "Rich Boy Hires The Poor Girl As Fake Girlfriend And Falls Real",
    "Contract Marriage Of Convenience Becomes A Real Love Story",
    "Heiress Pretends To Be Broke To Test Her New Boyfriend",
    "Heir Returns From Overseas And Falls For The Girl Running The Family Inn",
    "Estranged Heir Returns To Find The Town Foreman Is The Girl He Once Walked Away From",
    "Junior Lawyer Falls For The Founding Partner's Son During A Pro Bono Case",
    "Bookshop Owner Falls For The Quiet Customer Who Turned Out To Own The Block",
    "Scholarship Girl Tutors The CEO Who Funded Her Program",
    "Poor Mechanic Loved By The Heiress Of The Car Brand She Repairs",
    "Public School Teacher Loved By The Foundation Trustee Who Audits Her Class",
    "Translator Falls For The Foreign-Returned Heir She Was Hired To Help",
    "Animal Shelter Volunteer Falls For The Vet Heir Doing Pro Bono Hours",
    "Poor Lover Walks Into The Charity Auction And Outbids The Family",
    "Heir Stays In The Backpacker Hostel She Runs After Missing His Flight",
    "She Loved A Billionaire Who Tracked Her Every Move",
    "Possessive Heir Locks Her Out Of Every Other Choice",
    "Toxic Tycoon Calls It Love While She Counts Each Bruise In Words",
    "She Walks Out Of The Penthouse And He Burns The Bridges Behind Her",
    "Jealous Heir Drives Away Every Friend She Has Left",
    "The Billionaire Who Watched Her From Across Three Cities",
    "Forty-Year-Old Founder Loved By His Twenty-Two-Year-Old Intern",
    "Widowed Tycoon Falls For His Late Wife's Younger Sister",
    "Older Heir Confesses To The Daughter Of His Oldest Friend",
    "Younger Heir Loved By The Older Career Woman Who Taught Him The City",
    "Mature Billionaire Falls For The Music Student Half His Age",
    "Younger Tycoon Loves The Single Mother Eight Years Older Than Him",
    "Veteran Lawyer Loved By The Junior Half Her Age",
    "She Ran Away From The Wedding And Started Over In A Coastal Town",
    "Heir Disappeared To Escape The Marriage His Family Arranged",
    "She Faked Her Own Disappearance To Escape The Heir Who Loved Her Wrong",
    "He Boarded A Train To Anywhere Just To Outrun Her Memory",
    "She Hid In A Mountain Village Until His Helicopter Found Her",
    "Heir Quits His Family Empire And Vanishes Into A Fishing Town",
    "Runaway Bride Becomes The Coffee Shop Owner Who Refused His Money",
    "She Said No At The Altar And Took A Plane To A Country Without His Family",
    "He Followed Her To The End Of A Continent To Apologize For Loving Her The Wrong Way",
    "Childhood Friends Reunite As The Heir And The Working Class Single Mom",
    "First Love Returns As The Heir And The Widowed Bookshop Owner",
    "Reunited After A Decade Apart When She Catered His Family Wedding",
    "Forbidden Romance Between The Heir And His Father's Mistress's Daughter",
    "Forbidden Love Between The Heiress And Her Bodyguard",
    "Heir And His Brother's Ex-Fiancée Find Each Other Years Later",
    "Heir Falls For The Doctor Treating His Estranged Father",
    "Trauma-Bonded Romance Between The Heir And The Survivor He Pulled Out Of A Wreck",
    "Therapy Patient And The Therapist's Sister Cross Lines Slowly",
    "Heir Returns To The Hometown He Once Burned And Falls For The Girl He Hurt",
    "Estranged Husband Returns Begging For The Wife He Threw Away",
    "Mistreated Wife Walks Out And The Tycoon Husband Spends Five Years Earning Her Back",
    "She Granted Him A Divorce And He Realised Too Late What He Lost",
    "He Mistook Her Devotion For Obligation Until She Stopped Showing Up",
    "Toxic Wife Of The Tycoon Wakes Up After A Coma Into A Healthier Love",
    "Coercive Love Letter Reframed As Stalking After She Reads It Out Loud",
    "Heir Spent Years Trying To Reconnect After She Stopped Answering",
    "Heir Loves A Woman With A Restraining Order Against His Cousin",
    "He Said He Loved Her While Forbidding Her From Working",
    "She Smiled In The Photos And Plotted Her Quiet Exit",
    "Lonely Widow Loved By Her Stepson's Best Friend",
    "Heir Falls For The Single Father Raising His Niece",
    "Heir Loves The Woman Who Once Refused His Family's Hush Money",
    "Billionaire Single Father Falls For The Only Teacher His Son Will Speak To",
    "Tycoon Loses His Voice After A Trauma And Falls For The Sign Language Tutor",
    "Billionaire Checks Into A Psych Ward Under A Fake Name And Falls For The Night Nurse",
    "Heir Loses Five Years Of Memory Including The Wife He Married For Love",
    "She Was Hired As His Bone Marrow Donor And He Came Looking For Her After",
    "He Disappeared For Three Years And Returned To Find Her Engaged To Another Man",
    "Ninety-Nine Day Marriage Contract And Neither Wants To Count The Last Day",
    "Billionaire Joins A Blind Dating Show Disguised As An Office Worker",
    "She Signed A Sugar Arrangement For Med School And He Broke Every Rule First",
    "Snowed In For Three Days With The Billionaire She Just Told Off",
    "Childhood Betrothal She Ran From And He Tracked Her Down To Set Her Free",
    "Heir's Best Friend's Little Sister Confesses Ten Years After The Funeral",
    "Billionaire Grandfather's Will Forces Him To Marry The Girl He Never Met",
    "Twin Sister Ran Away On Wedding Day And She Took The Veil Instead",
    "Billionaire Lost Everything For Six Months And She Loved Him At Rock Bottom",
    "Auditor Sent To Investigate The CEO Falls For The Man Behind The Numbers",
    "She Was His Father's Best Friend's Daughter And He Waited Until She Was Ready",
    "Rich Heir Loses A Chess Bet And Becomes Her Bodyguard For A Year",
    "Billionaire Pretends To Be A Gardener At The Estate Of The Woman He Loves",
    "Heir Falls For The AI Researcher Maintaining The System That Holds His Late Father's Mind",
    "Hacker Girl From The Lower City Falls For The Megacorp Heir Who Hunts Her",
    "She Is The PR Strategist Who Made Him The Most Hated Man In The Country To Protect Him",
    "He Is The Only Patient She Cannot Remain Clinical About",
    "Billionaire Hires Her As A Fake Wife For A Board Review And Forgets To Count The Days",
    "She Feeds The Billionaire Who Pretends To Be Broke At Her Night Market Stall",
    "Heir Returns From War And The Physiotherapist Refuses To Treat Him Like Glass",
    "Billionaire Falls For The Woman Who Donated Blood That Saved His Life At Seventeen",
    "She Walked Into His Penthouse As The Replacement Bride And Walked Out As The One He Chose",
  ],
  humiliation_revenge_justice: [
    "They Mocked The Cleaner At The Investor Meeting",
    "Waitress Accused Over A Staged Missing Receipt",
    "Poor Intern Blamed For The CEO's Mistake",
    "Delivery Girl Humiliated During A Livestream",
    "Receptionist Fired Before The Audit Starts",
    "Bride Shamed At The Dress Fitting",
    "Poor Student Kicked Out Of The Team Photo",
    "Office Assistant Called Useless Before The Pitch",
    "Chef's Helper Blamed For A VIP Allergy",
    "Hotel Maid Framed By A Missing Necklace",
    "Single Woman Mocked At The Luxury Open House",
    "Cleaner Denied Entry To Her Own Building",
    "Junior Designer's Work Stolen Before Demo Day",
    "Factory Girl Shamed At The Product Launch",
    "They Laughed When Her Card Declined",
    "Security Guard Mocked The Woman Who Signed His Paycheck",
    "Nurse Blamed For A Rich Patient's Family Lie",
    "Cashier Humiliated By A Viral Customer Video",
    "They Called Her Just A Temp Before The Merger",
    "Poor Applicant Rejected In Front Of The Board",
    "Influencer Frames A Waitress For Clout",
    "Manager Deletes Her Name From The Award",
    "Wedding Planner Steals Credit From The Bride",
    "Neighborhood Council Shames The Wrong Woman",
    "Airport Staff Downgrade The Woman Who Owns The Airline Shares",
    "Store Manager Accuses The Wrong Cleaner",
    "Rich Client Publicly Rates Her Like A Servant",
    "Coworkers Laugh At Her Secondhand Dress",
    "They Refuse Her Refund Until The Cameras Roll",
    "The Room Turns Silent When Her Evidence Plays",
    "Viral Video Cleared The Woman They Shamed",
    "Urban Lawsuit Forced The Rich Client's Apology",
    "Public Evidence Reversed The Restaurant Humiliation",
    "Thriller Trial Exposed The Staged Receipt",
    "The Apology Livestream Came After Her Proof",
    "City Hall Cameras Cleared The Cleaner",
    "They Told Her To Use The Service Elevator",
    "Board Erased Her Name From The Patent",
    "Rich Wife Threw Coffee At The Waitress",
    "Volunteer Blamed For The Charity Shortfall",
    "They Made Her Apologize To The Real Thief",
    "Landlord Shamed Her Rent Slip At The Party",
    "Tutor Mocked In Front Of The Rich Parents",
    "Seamstress Accused Of Copying Her Own Design",
    "They Read Her Salary Aloud To Embarrass Her",
    "Caterer Blamed For The Client's Broken Vase",
    "Interpreter Called A Fraud Mid-Conference",
    "Barista Fired Over A Regular's False Claim",
    "Ticket Agent Blamed For The Heir's Late Arrival",
    "They Mocked Her Dialect At The Shareholder Call",
    "Gallery Assistant Accused Of Scratching The Art",
    "Housekeeper Framed For The Missing Watch",
    "They Laughed At Her Resume In The Group Chat",
    "Rival Leaked Her Draft As Plagiarism",
    "Warehouse Girl Blamed For The Recall",
    "Audit Trail Named The Executive Who Lied",
    "Recorded Meeting Cleared The Blamed Intern",
    "Her Timestamped Files Ended The Smear",
    "The Whistle Report Reopened Her Case",
  ],
  secret_identity_hidden_heiress: [
    "Hidden Heiress Works As A Hotel Maid",
    "CEO Daughter Goes Undercover As An Intern",
    "Famous Singer Hides At A School Talent Show",
    "Owner Pretends To Be A Janitor",
    "Heiress Joins Her Ex's Company As An Assistant",
    "Secret Investor Sits In The Back Of The Pitch Room",
    "Billionaire's Daughter Pretends To Be A Scholarship Girl",
    "Lady Boss Works The Front Desk For One Week",
    "Hidden CEO Becomes A Delivery Driver",
    "Heiress Hides Her Identity Until The Wedding",
    "Undercover Auditor Serves Coffee To The Board",
    "Secret Founder Is Mistaken For A Temp",
    "Pop Star Disguises Herself As A Nanny",
    "Lost Heiress Returns As A Nurse",
    "Company Owner Poses As A Cleaner During Layoffs",
    "Secret Shareholder Is Kicked Out Of The Photo",
    "Bodyguard Waits Until The Bullies Cross A Line",
    "Hidden Tycoon Marries In Secret For Protection",
    "Famous Actress Pretends To Be Broke After A Scandal",
    "Heiress Audits A Luxury Store As A Customer",
    "Secret Judge Watches The Competition From Backstage",
    "Undercover Lawyer Joins Her Husband's Firm",
    "Real Boss Is Mistaken For The Catering Staff",
    "Heiress Hides In The Dorm To Expose A Clique",
    "Billionaire Widow Enters The Family Company As A Clerk",
    "Secret Brand Owner Tests A Racist Boutique",
    "Hidden Doctor Is Treated Like A Charity Case",
    "Owner's Daughter Takes The Night Shift",
    "Secret CEO Lets Her Rival Sign The Wrong Papers",
    "No One Knows The Poor Bride Controls The Trust",
    "Lost Heiress Worked The Hotel Night Shift",
    "Urban Romance With The Secret Owner",
    "Undercover Heiress Audited The Wedding Hotel",
    "The Lost Daughter Signed The Ownership Proof",
    "Secret Owner Was Mistaken For A Maid",
    "Hidden Heiress Revealed The Family Vault",
    "Disguised Chairwoman Joins Her Own Factory Line",
    "Secret Franchise Owner Applies As A Cashier",
    "Undercover Board Member Takes The Mailroom Job",
    "Hidden Landlord Rents A Room In Her Building",
    "Masked Donor Volunteers At The Shelter She Funds",
    "Secret Composer Auditions For Her Own Orchestra",
    "Incognito Chef Trains Under Her Own Restaurant",
    "Hidden Publisher Interns At Her Own Imprint",
    "Real Owner Cleans The Suite She Secretly Holds",
    "Disguised Investor Pitches To Her Own Fund",
    "Secret Heir Drives The Company Shuttle",
    "Hidden Principal Shadows The Class That Bullies",
    "Undercover Airline Owner Checks Bags At Gate Nine",
    "Secret Fashion Mogul Models As A Fitting Girl",
    "Hidden Hospital Trustee Wheels Carts On Night Shift",
    "Disguised Heiress Waits Tables At Her Rival's Gala",
    "Secret Vineyard Owner Picks Grapes With The Crew",
    "Undercover Bank Heir Queues As An Ordinary Client",
    "Hidden Studio Boss Auditions For A Background Role",
    "Ownership Certificate Ended The Impostor's Claim",
    "The Reading Of The Trust Exposed The Fake Heir",
    "Her Signature On The Deed Silenced The Room",
    "Hidden Shareholder Voted Herself Back In",
    "The Sealed Will Revealed The Real Owner",
  ],
  toxic_family_betrayal: [
    "Mother Kicks Out The Daughter Who Paid The Bills",
    "Stepmother Steals The Inheritance File",
    "Golden Child Sells The Family House",
    "Daughter Locked Out After Paying The Mortgage",
    "Sister Fakes Debt To Take The Family Shop",
    "Parents Choose The Rich Brother At The Loan Office",
    "Mother-In-Law Changes The Locks During Custody Week",
    "Brother Hides The Father's Last Letter",
    "Family Sells Her Wedding Dress For Debt",
    "Aunt Uses Care Records To Erase Her",
    "Stepfamily Rewrites The Family Business Payroll",
    "Parents Abandon Her Child To Protect Their Image",
    "Mother Takes Credit For The Daughter's Business",
    "Sister Steals Her Identity For A Marriage Deal",
    "Brother Empties The Joint Account Before Rent Day",
    "Family Calls Her Useless Until Rent Is Due",
    "Mother-In-Law Takes The Baby's Documents",
    "Stepmother Forces Her Out Before The Lawyer Arrives",
    "Parents Hide Her Adoption Papers",
    "Sibling Frames Her For Grandmother's Missing Jewelry",
    "Family Demands Forgiveness After She Becomes Their Boss",
    "They Remove Her Name From The Deed",
    "Mother Uses School Forms To Control Her",
    "Brother's Wife Sells Her Mother's Keepsakes",
    "Family Betrays Her At The Store Reopening",
    "Stepfamily Burns The Care Agreement",
    "Father Leaves A Secret Clause They Ignored",
    "Toxic Mother Begs After The Company Collapses",
    "Sister Marries Her Ex To Take The House",
    "The Lawyer Finds Her Name On The Deed",
    "Mother-In-Law Hid The Custody Papers",
    "Family Thriller Exposed The Adoption Fraud",
    "Inheritance Deed Cleared The Scapegoat Daughter",
    "Sister Sold The House Before The Probate Hearing",
    "Custody Ledger Trapped The Golden Child",
    "The Fraud Hearing Returned Her Family Name",
    "Uncle Forges Her Signature On The Land Sale",
    "Cousin Claims The Scholarship Meant For Her",
    "Grandmother's Nurse Hides The Real Will",
    "Family Group Chat Plans Her Eviction",
    "Sister Reports Her To Take The Store Lease",
    "Mother Cancels Her Health Card Out Of Spite",
    "Stepbrother Sells Her Late Father's Workshop",
    "In-Laws Change The Baby's Surname Behind Her Back",
    "Family Uses Her Savings For The Golden Son's Bail",
    "Aunt Spreads A Lie To Break Her Engagement",
    "Parents Sign Her Business Over To The Favored Twin",
    "Sister Empties The Funeral Fund She Raised",
    "Family Locks Her Out Of The Ancestral Shop",
    "Stepmother Burns Her Acceptance Letter",
    "Brother Pawns Their Mother's Wedding Ring",
    "Relatives Vote Her Out Of The Family Firm",
    "Cousin Frames Her For The Missing Trust Money",
    "Mother-In-Law Fakes An Illness To Keep The House",
    "Family Demands Her Bonus Then Calls Her Selfish",
    "The Notarized Deed Proved She Owned The Home",
    "A Bank Record Exposed The Sibling's Theft",
    "The Care Log Cleared The Daughter They Blamed",
    "The Original Will Surfaced At The Reunion",
    "Her Recorded Call Ended The Inheritance Lie",
  ],
  cheating_ex_wedding_drama: [
    "Husband Cheats On The Plane Before Landing",
    "Mistress Takes The Bride's Hotel Room",
    "Ex Returns On The Wedding Day Too Late",
    "Fiance Leaves Her For Her Sister",
    "Backup Bride Discovers The Invoice",
    "Best Friend Calls The Bride A Thief",
    "Groom Runs Away With The Wedding Deposit",
    "Mistress Wears The Bride's Dress",
    "Husband Brings His Mistress Home",
    "Ex Wants Custody After She Becomes Rich",
    "Cheating Husband Signs The Wrong Divorce Papers",
    "Bride Finds The Second Wedding Website",
    "Fiance Uses Her House For His Mistress",
    "Groom's Family Replaces Her At Rehearsal Dinner",
    "Ex Crashes The Engagement Livestream",
    "Mistress Posts Photos Before The Ceremony",
    "Husband Hides Shared Debt In Her Name",
    "Bride Learns She Funded The Affair",
    "Groom Marries Her For The Company Shares",
    "Fiance Dumps Her At The Airport Gate",
    "Best Man Knows The Bride's Secret",
    "Divorce Papers Arrive During The Toast",
    "Ex Begs Her To Save His Business",
    "Mistress Uses The Baby Lie To Enter The House",
    "Wedding Planner Helps The Other Woman",
    "Husband Cheats During Her Mother's Surgery",
    "Bride Ends The Marriage Before The First Dance",
    "Ex Returns After The Prenup Deadline",
    "Fiance's Family Calls Her A Temporary Bride",
    "She Cancels The Wedding And Buys The Venue",
    "Mistress Took The Bride's Name",
    "Dark Romance Divorce Papers Saved Her",
    "Ex-Wife Returned At The Wedding Reveal",
    "Runaway Bride Bought The Chapel Back",
    "Her Revenge Marriage Exposed The Affair",
    "The Mistress Lost The Prenup War",
    "He Called Surveillance Love Until She Read The Vows Aloud",
    "Possessive Husband Lost The Day She Filed Quietly",
    "He Married Her For Revenge And Fell Too Late",
    "Obsessive Ex Reframed Control As Devotion",
    "The Prenup Clause He Used To Cage Her Set Her Free",
    "She Named The Control Out Loud At The Altar",
    "Groom Texts His Mistress During The Vows",
    "Bride Finds The Affair Receipts In The Gift Box",
    "Fiance Cancels The Honeymoon To Fund His Affair",
    "Best Friend Wears White To Steal The Groom",
    "Husband Registers The House Under The Mistress",
    "Ex Shows Up With A Baby At The Reception",
    "Bride Overhears The Toast Rehearsal Insult",
    "Groom's Mother Hands Her A Resignation Letter",
    "Cheating Fiance Blames Her For His Debt",
    "Mistress Live-Streams From The Bridal Suite",
    "Husband Files First To Take The Business",
    "Ex Returns The Ring With A Court Summons",
    "Wedding Singer Recognizes The Groom's Other Fiancee",
    "Bride Swaps The Vows For A Confession",
    "Groom's Assistant Warns Her At The Rehearsal",
    "Mistress Signs The Guestbook As The New Wife",
    "The Deleted Messages Resurfaced Before The Toast",
    "Her Quiet Prenup Clause Undid His Affair",
  ],
  single_mom_poor_woman_comeback: [
    "Single Mom Mocked At The School Fee Office",
    "Poor Mother Saves A Billionaire's Child",
    "Her Child Reveals The Real Father",
    "Abandoned Wife Becomes The CEO",
    "They Laugh At The Single Mom's Uniform",
    "Single Mom Fired For Leaving To The Clinic",
    "Poor Mother Denied A School Trip Deposit",
    "Child's Drawing Exposes The Liar",
    "Ex Wants Custody After Her Promotion",
    "Single Mom Builds The App They Rejected",
    "Poor Woman Works Nights To Save The Company",
    "Her Son Calls The CEO Dad By Accident",
    "Single Mom Delivers Food To Her Ex's Party",
    "Abandoned Wife Buys The Apartment Building",
    "Poor Mother Shamed At The Pediatric Desk",
    "Boss Mocked Her Childcare Schedule",
    "Her Daughter Records The Office Lie",
    "Single Mom Replaces The Founder Who Stole Her Idea",
    "Poor Mother Protects A Rich Heir In Secret",
    "Ex-Husband Uses School Gossip Against Her",
    "Single Mom Wins The Contract In Her Work Apron",
    "Her Child Finds The Missing Receipt",
    "Poor Woman Saves The Hospital Fundraiser",
    "Single Mom Refuses The CEO's Pity Money",
    "They Mock Her Grocery Coupons At The Gala",
    "Abandoned Wife Turns The Family Shop Into A Chain",
    "Single Mom's Sick Child Knows The Truth",
    "Poor Mother Outsmarts The Custody Lawyer",
    "Her Babysitter Secretly Works For The Rival",
    "Single Mom Walks Into The Boardroom With Receipts",
    "Single Mom Won The Custody Hearing",
    "Urban Romance Saved The Daycare Mom",
    "Secret Child Exposed The CEO's Lie",
    "Poor Mother Built The Comeback App",
    "Daycare Cameras Cleared The Working Mom",
    "Custody Threat Turned Into Her Victory",
    "Single Mom Turned Away At The Private School Gate",
    "Her Toddler Names The Investor As Grandpa",
    "Poor Mother Pawns Her Ring For The School Trip",
    "Boss Docks Her Pay For A Sick Child Day",
    "Single Mom Rebuilds The Brand That Fired Her",
    "Her Daughter's Essay Exposes The Landlord",
    "Poor Widow Denied Her Late Husband's Pension",
    "Single Mom Cleans The Office She Later Runs",
    "Ex Hides Income To Cut Her Child Support",
    "Her Son's Teacher Mocks The Free Lunch Card",
    "Poor Mother Wins The Grant They Laughed At",
    "Single Mom Sews Uniforms To Pay The Deposit",
    "The Nanny Cam Catches The Ex's Lie",
    "Poor Woman Returns As The Landlord's Boss",
    "Single Mom Outbids The Man Who Evicted Her",
    "Her Child's Hospital Bill Reveals The Fraud",
    "Poor Mother Refuses The Buyout And Keeps The Patent",
    "The School Ledger Cleared The Working Mom",
    "Her Comeback Contract Silenced The Gossip Table",
    "Single Mom Denied A Loan The Day She Files The Patent",
    "Her Kid's Field Trip Form Exposes The Payroll Fraud",
    "Poor Mother Buys The Diner That Refused Her Coupons",
    "Ex-Husband Begs For Custody After Her Stock Vests",
    "Single Mom Signs The Deal In Her Delivery Uniform",
  ],
  social_injustice_discrimination_drama: [
    "Disabled Woman Rejected At A Restaurant Entrance",
    "Manager Refuses Service Because Of Her Skin",
    "Pharmacy Accuses The Wrong Woman At Pickup",
    "Security Searches Her Bag In Public",
    "Bride Denied A Dress Because She Looks Poor",
    "Wheelchair User Blocked From The VIP Elevator",
    "Immigrant Nurse Mocked For Her Accent",
    "Pregnant Worker Denied A Chair During Shift",
    "Elderly Woman Refused At The Bank Counter",
    "Cleaner Blamed For A Customer's Lost Wallet",
    "Restaurant Ignores The Accessibility Policy",
    "Woman In Work Clothes Denied A Test Drive",
    "Mother Refused Entry With Her Service Dog",
    "Apartment Manager Rejects Her Family Name",
    "Teacher Frames A Scholarship Student",
    "Store Staff Follow Her Through Every Aisle",
    "Hospital Desk Delays Her Care For Insurance",
    "Boss Fires Her For Reporting Harassment",
    "Police Called On The Wrong Customer",
    "Airline Staff Separate A Disabled Passenger",
    "Cafe Owner Bans A Woman For Feeding A Stranger",
    "Luxury Spa Refuses A Scarred Customer",
    "Bank Manager Shames Her Small Deposit",
    "Restaurant Demands Proof She Can Pay",
    "Hotel Cancels Her Booking At Check-In",
    "Public Office Loses Her Complaint On Purpose",
    "Influencer Films Her Poverty Without Consent",
    "Mall Guard Removes The Wrong Teen",
    "Clinic Blames A Mother For Being Poor",
    "Policy Review Exposes The Discrimination Room",
    "Restaurant Refused The Owner In A Wheelchair",
    "Urban Thriller Exposed The Racist Manager",
    "Accessibility Lawsuit Returned Her Seat",
    "Classism At The Bank Became Public Evidence",
    "Discrimination Complaint Reopened The Hotel Case",
    "Bystander Video Cleared The Woman They Framed",
    "Deaf Customer Refused Service At The Ticket Window",
    "Manager Denies A Prayer Break On The Floor",
    "Wheelchair Ramp Locked During The Grand Opening",
    "Store Accuses A Blind Woman Of Shoplifting",
    "Landlord Rejects Tenants With Foreign Names",
    "Gym Cancels Her Pass Over A Visible Scar",
    "Bank Flags Her Account For Her Neighborhood",
    "Clinic Sends The Uninsured Mother To The Back",
    "Waiter Adds A Surcharge Only To Her Table",
    "School Bars A Student For Her Religious Dress",
    "Rideshare Cancels On The Woman With A Cane",
    "Boutique Locks The Case When She Walks In",
    "HR Buries Her Discrimination Complaint Twice",
    "Elderly Man Denied A Refund For Confusion",
    "Restaurant Seats Her By The Kitchen Every Time",
    "Housing Office Loses Her Wheelchair Request",
    "Pharmacist Questions Her Prescription Aloud",
    "Interviewer Mocks The Gap For Her Caregiving",
    "The Access Audit Reopened The Store Case",
    "Her Recording Ended The Manager's Excuses",
    "City Council Rewrote The Policy After Her Video",
    "The Settlement Named Every Staff Who Watched",
  ],
  workplace_ceo_power_struggle: [
    "Intern Became The CEO After They Fired Her",
    "Assistant Saved The Company And Lost Her Name",
    "They Stole Her Pitch Deck Before Demo Day",
    "CEO Fired The Wrong Woman In Front Of HR",
    "Startup Founder Was Erased From The Cap Table",
    "She Was Laid Off Before The Board Needed Her",
    "Office Clique Mocked The Temp Who Owned The Patent",
    "Boss Took Her Credit Then Begged For The File",
    "Receptionist Walked Into The Boardroom As Owner",
    "They Deleted Her Name From The Product Launch",
    "The Coffee Girl Wrote The Acquisition Plan",
    "HR Humiliated Her Before The Audit Began",
    "Coworkers Laughed At Her Badge Color",
    "She Signed Their Paychecks After They Fired Her",
    "Investor Meeting Exposed The Stolen Prototype",
    "Toxic Boss Blamed Her For His Failed Deal",
    "She Was Removed From The Team Photo Before IPO",
    "Junior Designer Owned The Brand They Sold",
    "They Mocked Her Side Hustle Until It Bought Them",
    "The Office Cleaner Knew The Merger Secret",
    "She Was Demoted For Reporting The CEO's Lie",
    "Coworker Stole Her Code Before The Release",
    "Startup War Room Needed The Woman They Excluded",
    "She Lost Her Desk And Won The Company Vote",
    "Boss Called Her Replaceable During All Hands",
    "They Fired The Whistleblower Before The Regulator Arrived",
    "She Was Just A Contractor Until The Board Read The Logs",
    "The Layoff List Had The CEO's Daughter On It",
    "She Bought The Company That Rejected Her Resume",
    "The Slack Archive Destroyed The Office Lie",
    "Hostile Board Needed The Fired Assistant",
    "Urban CEO War Exposed The Cap Table Fraud",
    "Pitch Theft Failed At The Acquisition Vote",
    "Assistant Took Back The Hostile Takeover",
    "Boardroom Evidence Restored Her Founder Shares",
    "The Boss Needed The Woman He Laid Off",
    "Contract Wife For The CEO Heir",
    "Hiding Twins From The Ruthless Billionaire",
    "After Divorce She Bought His Company",
    "One Night With The Wrong CEO",
    "The CEO's Paper Bride Refused To Sign",
    "Ex-Wife Returned As A Female Billionaire",
    "Pregnant After A Deal With Her Boss",
    "Secretary Married The Heartless CEO On Paper",
    "The Ruthless Billionaire Regretted The Divorce",
    "Hidden Baby Exposed The CEO's Family Lie",
    "Possessive Boss Bought The Company She Built",
    "Surrogate Wife Owned The Heir Contract",
    "Accidental Marriage With Her Cold CEO",
    "The Billionaire's Ex-Wife Became His Investor",
    "Twins Walked Into The CEO Boardroom",
    "Business Deal Bride Outsmarted The Billionaire",
    "One Weekend With Her Arrogant Billionaire Boss",
    "The CEO's Contracted Wife Held The Shares",
    "Secret Billionaire Heiress Married Her Boss",
    "Divorced Wife Returned With The Missing Heir",
    "Ruthless CEO Chased The Wife He Humiliated",
    "Paper Bride Saved The Billionaire's Merger",
    "The Boss's Hidden Woman Became The Buyer",
    "Pregnant Secretary Refused The CEO's Buyout",
    "Ex-Husband's Regret Came After Her IPO",
    "The Billionaire Playboy's Secret Baby",
    "Heartless CEO Needed His Unwanted Wife",
    "The Contract Bride Rewrote The Prenup",
    "After The One-Night Mistake She Owned The Hotel",
    "CEO Mistook His Wife For A Paid Actress",
    "Female Billionaire Bought Her Ex's Wedding Venue",
    "Ruthless Boss Fired The Woman Carrying His Heir",
    "The CEO's Fake Fiancee Was The Real Owner",
    "Divorce Papers Arrived Before The Acquisition",
    "Possessive Billionaire Lost His Contract Wife",
    "Hidden Identity Bride Walked Into The Shareholder Vote",
    "One-Night Bride Signed The Wrong CEO's Deal",
    "Pregnant Ex-Wife Crashed The Billionaire Gala",
    "The Billionaire's Babysitter Controlled The Trust",
    "Unwanted Wife Became The CEO's Rival",
    "The Cold CEO's Secret Child Found The Ledger",
    "The CEO's Maid Was A Secret Investor",
    "Revenge Queen Returned As His Board Chair",
    "The Billionaire's Contract Lover Chose Freedom",
    "Married On Paper To A Man She Did Not Recognize",
    "The Scandalous CEO Hid Their Twins",
    "After Divorce The Boss Begged For Her Signature",
    "The Billionaire's Lawful Wife Owned The Patent",
    "The CEO's Delicate Wife Was His Competitor",
    "Arrogant Billionaire Needed An Heir By Contract",
    "The Hidden Heiress Signed As His Secretary",
    "Ruthless Husband Learned His Wife Was The Lender",
    "Secret Baby Turned The Board Against The CEO",
    "The Ex-Wife's Revenge Tempted The Billionaire",
    "Business Contract Bride Became His Only Witness",
    "Pregnant Again For The CEO Who Rejected Her",
  ],
  medical_hidden_doctor_life_care: [
    "Hidden Surgeon Saved The Patient They Rejected",
    "They Mocked The Night Nurse Before The Operation",
    "Poor Patient Refused Care Until The Doctor Arrived",
    "Doctor In Disguise Was Treated Like A Charity Case",
    "The Chart Exposed The Rich Family's Lie",
    "Triage Desk Humiliated The Woman Who Built The Ward",
    "Nurse Blamed For A VIP Patient's Secret",
    "Resident Doctor Fired Before The Ethics Review",
    "She Was Called Just A Caregiver Before Surgery",
    "Hospital Donor Family Tried To Buy The Diagnosis",
    "Clinic Refused The Mother Who Saved The Surgeon",
    "Pharmacy Accused The Doctor's Daughter In Public",
    "They Delayed Her Care Because She Looked Poor",
    "Hidden Doctor Worked The Free Clinic Night Shift",
    "Surgeon Returned As A Patient Advocate",
    "The Consent Form Revealed Who Lied",
    "They Shamed The Nurse Until The Monitor Logs Spoke",
    "Poor Intern Knew The Treatment They Ignored",
    "Emergency Room Rejected The Woman Who Owned The Hospital",
    "Rich Patient's Family Framed The Ward Nurse",
    "She Saved A Child And Lost Her Badge",
    "Hospital Board Needed The Doctor They Suspended",
    "The Medication Log Cleared The Accused Nurse",
    "They Called Her Uninsured Before Reading Her Name",
    "Clinic Manager Hid The Complaint Until The Audit",
    "The Transplant List Exposed The Donor Bribe",
    "She Was The Specialist They Refused To Page",
    "Patient Advocate Beat The Hospital Cover Up",
    "The Ambulance Report Revealed The Truth",
    "Poor Woman Paid The Bill That Saved The Ward",
    "Hidden Surgeon Exposed The VIP Cover Up",
    "Medical Romance Began After The Chart Audit",
    "Malpractice Trial Needed The Nurse They Shamed",
    "Consent Form Saved The Poor Patient",
    "Thriller Ward Exposed The Donor Family",
    "Hospital Board Needed The Hidden Doctor",
    "Volunteer Medic Outranked The Chief Who Mocked Her",
    "They Skipped Her In Line Until The Code Blue Rang",
    "Rural Doctor Shamed At The City Hospital Gala",
    "The Billing Office Denied The Woman Who Funded The Wing",
    "Paramedic Ignored Until She Named The Missed Diagnosis",
    "Night Shift Nurse Caught The Error The Chief Signed",
    "They Called Her Overqualified Before The Emergency",
    "Insurance Desk Turned Away The Hospital's Silent Owner",
    "Medical Student Blamed For The Attending's Mistake",
    "Free Clinic Doctor Was The Surgeon They Fired",
    "The Rich Family Bribed To Skip The Transplant Queue",
    "She Read The X-Ray No One Else Would Touch",
    "Volunteer Nurse Exposed The Falsified Consent",
    "Hospital Fired Her For Reporting The Unsafe Ward",
    "The Chart Note Proved She Warned Them First",
    "They Mocked Her Rural Degree Until The Rare Case",
    "Ambulance Crew Refused The Address In Her Neighborhood",
    "The Ethics Board Needed The Whistleblower They Silenced",
    "Charity Patient Turned Out To Own The Clinic Chain",
    "Pharmacist Refused Her Script Until The Doctor Signed",
    "Her Handover Notes Cleared The Blamed Resident",
    "The ICU Log Exposed The VIP Queue-Jump",
    "Care Home Aide Saved The Heir Who Ignored Her",
  ],
  school_campus_bullying_identity: [
    "Scholarship Girl Owned The School They Mocked",
    "Bullies Mocked The New Girl Until Her Bodyguard Arrived",
    "No One Knew Her Father Funded The Campus",
    "Talent Show Revealed The Girl They Laughed At",
    "The Donor's Daughter Pretended To Be Poor",
    "They Kicked Her Out Of The Team Photo",
    "Class President Framed The Scholarship Student",
    "Dorm Clique Shamed The Girl Who Signed Their Grants",
    "Rich Students Mocked The Janitor's Son",
    "She Was Removed From Debate Before The Judge Arrived",
    "Principal Protected The Bully Until The CCTV Played",
    "They Called Her A Cheater Before The Exam Metadata",
    "Campus Influencer Humiliated The Wrong Freshman",
    "Poor Student Owned The Lab They Locked",
    "Coach Benched The Girl Who Saved The Team",
    "Group Chat Destroyed The Bully's Perfect Image",
    "She Was Denied Scholarship Before The Ledger Opened",
    "The Transfer Student Hid A Famous Voice",
    "They Mocked Her Uniform At Graduation Rehearsal",
    "Donor Parent Tried To Expel The Wrong Girl",
    "Cafeteria Bullies Learned She Held Their Tuition",
    "Teacher Deleted Her Contest Entry",
    "Campus Queen Stole Her Research Poster",
    "She Was Just A Cleaner At Her Own School",
    "They Hid Her Name From The Honor Roll",
    "Student Council Shamed The Girl Who Owned The Venue",
    "She Went Undercover In Her Ex's Class",
    "The Scholarship Office Exposed The Rich Kid's Lie",
    "School Assembly Revealed The Bodyguard Log",
    "Graduation Stage Returned The Name They Erased",
    "Scholarship Girl Beat The Rich Clique",
    "Young Adult Campus Queen Lost The Group Chat",
    "Donor Parent Failed The Talent Show Reveal",
    "Rich Clique Framed The Transfer Student",
    "Scholarship Ledger Saved The Bullied Girl",
    "Campus Bullying Ended At Graduation",
    "They Doctored The Attendance To Expel The Poor Girl",
    "The Quiet Transfer Aced The Test They Said She Stole",
    "Rich Clique Locked Her Out Of The Group Project",
    "She Coached The Team That Benched Her For Charity",
    "The Reunion Revealed Who Really Wrote The Winning Essay",
    "They Mocked Her Lunch Card Until The Board Meeting",
    "Exchange Student Hid That She Owned The Scholarship Fund",
    "The Bully's Prank Video Cleared The Girl They Framed",
    "She Was Cut From Choir Before The National Judge Came",
    "Rich Parent Demanded The Teacher Fail The Wrong Student",
    "The Locker Note Exposed The Real Cheater",
    "Campus Queen Lost The Election To The Girl She Bullied",
    "They Called Her A Charity Case At The Alumni Dinner",
    "The Late Tutor Turned Out To Grade Their Finals",
    "She Reported The Hazing And Lost Her Dorm",
    "The Field Trip Left Behind The Girl Who Funded It",
    "Debate Rival Stole Her Case File Before Regionals",
    "The Yearbook Erased The Student Who Topped The Class",
    "They Laughed At Her Accent Until The Language Prize",
    "Coach Cut Her Before The Scout Read Her Record",
    "The Scholarship Committee Chair Was The Girl They Shamed",
    "Group Chat Screenshots Cleared The Blamed Freshman",
    "She Tutored The Bully Who Needed To Pass",
    "The Honor Court Reversed The Expulsion On Camera",
  ],
  werewolf_luna_alpha_soulmate: [
    "Rejected Luna Returned Under A Blood Moon",
    "The Alpha Regretted Rejecting His True Mate",
    "Moon Wolf Girl Was Called A Victim",
    "Her Soulmate Chose The Rival Luna",
    "The Pack Mocked The Girl Who Saved Them",
    "Alpha Banished His Mate Before The Eclipse",
    "The Luna Mark Awoke After Her Rejection",
    "Enemies Became Mates During The Pack Trial",
    "Second Chance Mate Returned With A Scar",
    "The Beta Protected The Luna He Could Not Claim",
    "Love Triangle Split The Moon Wolf Pack",
    "The Alpha's Bride Was The Wrong Wolf",
    "She Hid Her Wolf Until The Mating Ceremony",
    "Rival Luna Faked The Sacred Bond",
    "The Moon Council Shamed The True Mate",
    "Victim Girl Became The Pack's Strongest Wolf",
    "He Chose Duty And Lost His Luna",
    "Her Scent Mark Exposed The Alpha's Lie",
    "The Rogue Girl Saved The Alpha's Heir",
    "Pack Elders Rejected The Wrong Daughter",
    "The Blood Moon Revealed His Soulmate",
    "She Broke The Mate Bond To Save Herself",
    "Alpha King Kneels To The Rejected Luna",
    "The Wolf He Hated Was His Fate",
    "Moonlit Trial Returned Her Luna Name",
    "The Luna Refused A Cowardly Alpha",
    "Hidden Wolf Princess Entered The Pack Arena",
    "Her Rival Claimed A Bond That Wasn't Hers",
    "The Alpha Heard Her Wolf Too Late",
    "She Chose The Pack Over The Possessive Mate",
    "Rejected Omega Became The Luna",
    "Fated Mate Trial Exposed The Alpha",
    "Pack Law Saved The Rejected Luna",
    "Omega Girl Broke The False Mate Bond",
    "Alpha Regretted The Luna He Banished",
    "Rogue Pack Crowned The True Mate",
  ],
  steamy_alien_captive_romance: [
    "Alien Commander Claimed The Captive Who Defied Him",
    "The Human Slave Broke The Empire's Collar",
    "Possessive Alien King Needed The Woman He Caged",
    "She Refused To Kneel On The Dark Planet",
    "Dominant Alien Lord Lost Control Of His Captive",
    "The Arrogant Commander Bought The Wrong Human",
    "Alien Masters Marked The Woman Who Would Rule",
    "His Captive Rewrote The Obedience Contract",
    "Sensual Bond Formed In The Warship Cell",
    "The Human Translator Exposed The Alien Court",
    "She Survived The Auction And Claimed The Throne",
    "Alien Prince Called Her Property Until The Trial",
    "Dark Planet Queen Was Once His Prisoner",
    "The Possessive Warlord Chose Consent Too Late",
    "Her Collar Code Destroyed The Alien Master",
    "Opposites Attracted In The Command Deck",
    "The Captive Female Lead Outsmarted The Empire",
    "Alien Arena Crowd Mocked The Human Survivor",
    "She Turned The Slave Brand Into Evidence",
    "The Galactic Harem Rejected The Wrong Woman",
    "His Warship Needed The Captive's Blood Map",
    "The Alien King's Favorite Refused His Bedchamber",
    "She Made The Dominant Ruler Sign Her Freedom",
    "The Breeding Contract Failed Against Consent Law",
    "Alien Guard Protected The Captive Rebel",
    "Her Human Defiance Broke The Obedience Ritual",
    "The Planet Council Saw The Collar Logs",
    "Possessive Master Became Her Witness",
    "She Escaped The Pleasure Moon With His Ship",
    "The Dark Court Needed The Captive They Shamed",
    "Alien Emperor Signed Her Freedom",
    "Steamy Dark Romance On The Warship",
    "Captive Heroine Broke The Empire Contract",
    "Consent Restoration Defeated The Alien Master",
    "Dark Alien King Lost His Human Bride",
    "Possessive Warlord Freed The Woman He Claimed",
  ],
};
