export const MIN_TARGET_WORDS_PER_CHAPTER = 800;
export const DEFAULT_TARGET_WORDS_PER_CHAPTER = 2500;
export const MAX_TARGET_WORDS_PER_CHAPTER = 3000;
export const LONG_CHAPTER_TARGET_WORDS_THRESHOLD = 2000;
